language: go

go:
    - 1.3
    - 1.4
    - tip

before_install:
    - mkdir -p $HOME/gopath/src/gopkg.in
    - mv $HOME/gopath/src/github.com/go-conf/conf $HOME/gopath/src/gopkg.in/conf.v0
    - cd .
